-- PROGRAM		"Quartus II 64-Bit"
-- VERSION		"Version 15.0.0 Build 145 04/22/2015 SJ Web Edition"
-- CREATED		"Wed Sep 23 20:48:44 2015"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY light IS 
	PORT
	(
		x1 :  IN  STD_LOGIC;
		x2 :  IN  STD_LOGIC;
		f :  OUT  STD_LOGIC
	);
END light;

ARCHITECTURE bdf_type OF light IS 

SIGNAL	SYNTHESIZED_WIRE_0 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_1 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_2 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_3 :  STD_LOGIC;


BEGIN 



SYNTHESIZED_WIRE_2 <= SYNTHESIZED_WIRE_0 AND x2;


SYNTHESIZED_WIRE_3 <= x1 AND SYNTHESIZED_WIRE_1;


f <= SYNTHESIZED_WIRE_2 OR SYNTHESIZED_WIRE_3;


SYNTHESIZED_WIRE_1 <= NOT(x2);



SYNTHESIZED_WIRE_0 <= NOT(x1);



END bdf_type;