FROM ubuntu:latest

LABEL maintainer="jerry.liu1@se.com"

WORKDIR /home

RUN apt-get update

RUN apt-get install -y vim  
RUN apt-get install -y git
RUN apt-get install -y curl
RUN apt-get install -y sqlite3
RUN apt-get install -y net-tools
RUN apt-get install -y iputils-ping
RUN apt-get install -y tcpdump
RUN apt-get install -y iperf3
RUN apt-get install -y iproute2
RUN apt-get install -y iptables
RUN apt-get install -y openssh-server
RUN apt-get install -y openssh-client

RUN apt-get install -y python3
RUN apt-get install -y python3-keyring
RUN apt-get install -y python3-paramiko

RUN sysctl net.ipv4.conf.all.forwarding=1

RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]